#!/usr/bin/env bash

set -euo pipefail -x

shopt -s nullglob

BIN="target/debug/sonarr-script"

"$BIN" --eventtype=Test

export sonarr_eventtype="Download"
export sonarr_isupgrade="False"

rm test/media/*.srt || true
rm -rf test/media/.subtitles || true

for file in test/media/*.{mkv,mp4}; do
  export sonarr_episodefile_path="$PWD/$file"
  "$BIN"
done
