#!/usr/bin/env bash

set -euo pipefail -x

# Causes no-match glob to not be a string literal
shopt -s nullglob

mkdir -p "$PWD/test/bin"
rm test/bin/* || true
rm test/media/*.srt || true
rm -rf test/media/.subtitles || true

SRC="$PWD/target/debug/sonarr-script"
BIN="$PWD/test/bin/sonarr-subtitle-merge"
ln -s "$SRC" "$BIN"

"$BIN" --eventtype=Test

export sonarr_eventtype="Import"
export sonarr_isupgrade="False"

for file in test/media/*.{mkv,mp4}; do
  export sonarr_episodefile_path="$PWD/$file"
  "$BIN"
done
