version: "3"

tasks:
  default: task --list

  dry-clean:
    aliases: ["dc"]
    desc: Prints what would be deleted by "clean"
    cmds:
    - sl clean --print --ignored --files --dirs --exclude=test/media/*.{mkv,mp4}

  clean:
    aliases: ["c", "purge"]
    desc: Cleans the repo
    cmds:
    - sl clean --ignored --files --dirs --exclude=test/media/*.{mkv,mp4}

  build:
    aliases: ["b", "materialize"]
    desc: Builds the repo
    cmds:
    - cargo build --package sonarr-script

  test:
    aliases: ["t"]
    desc: Run tests
    deps:
    - build
    cmds:
    - test/sonarr-script

  image:
    aliases: ["i", "img"]
    desc: Builds container images
    cmds:
    - docker build . --file sonarr-script/Dockerfile --tag ghcr.io/pbar1/sonarr-script
