version: "3"

tasks:
  default: task --list

  dry-clean:
    aliases: ["dc"]
    desc: Prints what would be deleted by "clean"
    cmds:
    - sl clean --print --ignored --files --dirs --exclude=test/media/*.{mkv,mp4}

  clean:
    aliases: ["c", "purge"]
    desc: Cleans the repo
    cmds:
    - sl clean --ignored --files --dirs --exclude=test/media/*.{mkv,mp4}

  build:
    aliases: ["b", "materialize"]
    desc: Builds the repo
    deps:
    - clean
    cmds:
    - go build -C cmd/sonarr-subtitle-merge

  test:
    aliases: ["t"]
    desc: Run tests
    deps:
    - build
    cmds:
    - scripts/test-sonarr-subtitle-merge
