[package]
name = "sonarr-script"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
aspasia = "0.2"
clap = { version = "4", features = ["derive", "env"] }
dialoguer = "0.11"
regex = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
