#!/usr/bin/env bash

set -euo pipefail

shopt -s nullglob

export sonarr_eventtype="Download"

for file in test/media/*.{mkv,mp4}; do
  export sonarr_episodefile_path="$PWD/$file"
  ./cmd/sonarr-subtitle-merge/sonarr-subtitle-merge
done
